package ru.salestrainer.backend.service;

import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ru.salestrainer.backend.controller.ApiException;
import ru.salestrainer.backend.model.*;
import ru.salestrainer.backend.repository.*;
import java.time.Instant;
import java.util.*;

@Service
public class BackofficeQueryService {
    private final AppUserRepository users;private final PromptProfileRepository roles;private final AiCredentialRepository credentials;private final LiveSessionRepository sessions;private final AuditEventRepository audit;private final ClientRefreshTokenRepository refreshTokens;
    public BackofficeQueryService(AppUserRepository users,PromptProfileRepository roles,AiCredentialRepository credentials,LiveSessionRepository sessions,AuditEventRepository audit,ClientRefreshTokenRepository refreshTokens){this.users=users;this.roles=roles;this.credentials=credentials;this.sessions=sessions;this.audit=audit;this.refreshTokens=refreshTokens;}
    @Transactional(readOnly=true) public List<UserSummary> users(){Instant now=Instant.now();return users.findAllByOrderByLastNameAscFirstNameAsc().stream().map(u->new UserSummary(u.getId(),u.getLogin(),u.getFirstName(),u.getLastName(),u.getCompany(),u.getEmail(),u.isEnabled(),u.getPromptProfiles().size(),sessions.countActiveForUser(u.getId(),now),u.getLastLoginAt())).toList();}
    @Transactional(readOnly=true) public UserDetail user(Long id){AppUser u=users.findById(id).orElseThrow(()->ApiException.notFound("Пользователь не найден."));List<SessionView> recent=sessions.findTop30ByUser_IdOrderByStartedAtDesc(id).stream().map(this::session).toList();Instant now=Instant.now();List<DeviceView> devices=refreshTokens.findByUser_IdAndRevokedAtIsNullOrderByCreatedAtDesc(id).stream().filter(t->t.getExpiresAt().isAfter(now)).collect(java.util.stream.Collectors.toMap(ClientRefreshToken::getDeviceId,t->new DeviceView(t.getDeviceId(),t.getDeviceName(),t.isPersistent(),t.getCreatedAt(),t.getLastUsedAt(),t.getExpiresAt()),(a,b)->a.createdAt().isAfter(b.createdAt())?a:b,LinkedHashMap::new)).values().stream().toList();return new UserDetail(u.getId(),u.getLogin(),u.getFirstName(),u.getLastName(),u.getCompany(),u.getEmail(),u.isEnabled(),u.getPromptProfiles().stream().map(PromptProfile::getId).toList(),u.getCreatedAt(),u.getUpdatedAt(),u.getLastLoginAt(),recent,devices);}
    @Transactional(readOnly=true) public List<RoleView> roles(){return roles.findAllByOrderBySortOrderAscNameAsc().stream().map(p->new RoleView(p.getId(),p.getName(),p.getDescription(),p.getSystemPrompt(),p.getEvaluationPrompt(),p.getModel(),p.getEvaluationModel(),p.isEnabled(),p.getVersion(),p.getSortOrder(),p.getUpdatedAt())).toList();}
    @Transactional(readOnly=true) public List<CredentialView> credentials(){Instant now=Instant.now();return credentials.findAllByOrderByNameAsc().stream().map(c->new CredentialView(c.getId(),c.getName(),c.getProvider(),c.getKeyHint(),c.isEnabled(),c.getMaxConcurrentSessions(),sessions.countLeasedForCredential(c.getId(),now),c.getHealthStatus(),c.getLastError(),c.getLastCheckedAt(),c.getUpdatedAt())).toList();}
    @Transactional(readOnly=true) public List<SessionView> sessions(){return sessions.findTop200ByOrderByStartedAtDesc().stream().map(this::session).toList();}
    @Transactional(readOnly=true) public Dashboard dashboard(){Instant now=Instant.now();long eu=users.findAll().stream().filter(AppUser::isEnabled).count();long er=roles.findAll().stream().filter(PromptProfile::isEnabled).count();long ek=credentials.findAll().stream().filter(AiCredential::isEnabled).count();long cap=credentials.findAll().stream().filter(AiCredential::isEnabled).mapToLong(AiCredential::getMaxConcurrentSessions).sum();return new Dashboard(eu,er,ek,cap,sessions.countActive(now));}
    @Transactional(readOnly=true) public List<AuditView> audit(){return audit.findTop100ByOrderByCreatedAtDesc().stream().map(a->new AuditView(a.getId(),a.getCreatedAt(),a.getEventType(),a.getActor(),a.getSubject(),a.getDetail())).toList();}
    private SessionView session(LiveSession s){return new SessionView(s.getId(),s.getStatus(),s.getUser().getId(),s.getUser().getDisplayName(),s.getUser().getCompany(),s.getPromptProfile().getId(),s.getPromptProfile().getName(),s.getAiCredential().getName(),s.getDeviceId(),s.getClientVersion(),s.getStartedAt(),s.getActivatedAt(),s.getClosedAt(),s.getCompletionSource(),s.getScore(),s.getEvaluationSummary(),s.getTranscript(),s.getEvaluationJson(),s.getCloseReason());}
    public record UserSummary(Long id,String login,String firstName,String lastName,String company,String email,boolean enabled,int roleCount,long activeSessions,Instant lastLoginAt){} public record UserDetail(Long id,String login,String firstName,String lastName,String company,String email,boolean enabled,List<Long> roleIds,Instant createdAt,Instant updatedAt,Instant lastLoginAt,List<SessionView> recentSessions,List<DeviceView> devices){} public record DeviceView(String deviceId,String deviceName,boolean persistent,Instant createdAt,Instant lastUsedAt,Instant expiresAt){}
    public record RoleView(Long id,String name,String description,String livePrompt,String evaluationPrompt,String liveModel,String evaluationModel,boolean enabled,int version,int sortOrder,Instant updatedAt){} public record CredentialView(Long id,String name,String provider,String keyHint,boolean enabled,int maxConcurrentSessions,long activeSessions,String healthStatus,String lastError,Instant lastCheckedAt,Instant updatedAt){}
    public record SessionView(UUID id,String status,Long userId,String userName,String company,Long roleId,String roleName,String credentialName,String deviceId,String clientVersion,Instant startedAt,Instant activatedAt,Instant closedAt,String completionSource,Integer score,String evaluationSummary,String transcript,String evaluationJson,String closeReason){} public record Dashboard(long enabledUsers,long enabledRoles,long enabledCredentials,long totalCapacity,long activeSessions){} public record AuditView(Long id,Instant createdAt,String eventType,String actor,String subject,String detail){}
}
